// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cmFSfo-zhRc1vcfGmFsAKjI6kDxZIHw',
    appId: '1:619840719317:web:43ab6e26378a731844955c',
    messagingSenderId: '619840719317',
    projectId: 'chat-c502f',
    authDomain: 'chat-c502f.firebaseapp.com',
    storageBucket: 'chat-c502f.appspot.com',
    measurementId: 'G-EBLSNP8Y4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZ2lE0sj_tSsPWpbPydhrOQhuXVzvEBo',
    appId: '1:619840719317:android:72a73eef2bdb8d9244955c',
    messagingSenderId: '619840719317',
    projectId: 'chat-c502f',
    storageBucket: 'chat-c502f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNBvfktIfyq5dkxOe02JfEI3XU3e0CsPw',
    appId: '1:619840719317:ios:f3e9a2cc772515a044955c',
    messagingSenderId: '619840719317',
    projectId: 'chat-c502f',
    storageBucket: 'chat-c502f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNBvfktIfyq5dkxOe02JfEI3XU3e0CsPw',
    appId: '1:619840719317:ios:5c6793d42996100c44955c',
    messagingSenderId: '619840719317',
    projectId: 'chat-c502f',
    storageBucket: 'chat-c502f.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
